apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  namespace: services
spec:
  type: NodePort
  ports:
    - name: http
      port: 8092
      nodePort: 30092
      targetPort: 8092