apiVersion: v1
kind: Service
metadata:
  name: configuration-service
  namespace: services
spec:
  type: NodePort
  ports:
    - name: http
      port: 8091
      nodePort: 30091
      targetPort: 8091